apiVersion: v1
kind: Service
metadata:
  name: {{ include "trento-web.fullname" . }}
  labels:
    {{- include "trento-web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webService.type }}
  ports:
    - port: {{ template "trentoWeb.port" . }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "trento-web.selectorLabels" . | nindent 4 }}
