---
- name: Get /etc/corosync/corosync.conf md5 hash 
  command: md5sum /etc/corosync/corosync.conf
  #command: md5sum /tmp/test
  register: corosync_md5_content

- name: Set corosync.conf hash to the varuable corosync_file_md5
  set_fact:
  corosync_file_md5: "{{ corosync_md5_content.stdout }}"
  delegate_facts: True

- name: "{{ name }}.check"
  assert:
    that:
      - "{{ groups[item] | map('extract', hostvars) | map(attribute='corosync_file_md5') | list | unique | length }} == 1"
  loop: "{{ group_names }}"
  tags:
    - "check:1.1.10:Check if corosync configuration file is the same in all cluster nodes"
    - "group:1.1:Corosync"
    - |
      description:
      ## Remediation
      Use the same /etc/corosync/corosync.conf configuration file in all cluster nodes
  check_mode: false
  register: config_updated
  changed_when: config_updated.rc != 0
  failed_when: config_updated.rc > 1

- block:
    - name: Post results
      import_role:
        name: post-results
  when:
    - ansible_check_mode
  vars:
    status: "{{ config_updated is not changed }}"
