---

- name: "{{ name }}.check"
  assert:
    that:
      - "{{ groups[item] | map('extract', hostvars) | map(attribute='corosync_file_md5') | list | unique | length }} == 1"
  loop: "{{ group_names }}"
