#!BuildTag: trento/trento-server:0.3.4
#!BuildTag: trento/trento-server:0.3.4-build%RELEASE%
apiVersion: v2
name: trento-server
description: The trento server chart contains all the components necessary to run a Trento server.
type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates
version: 0.3.4

dependencies:
  - name: trento-web
    version: ">0.0.0"
    condition: trento-web.enabled
  - name: trento-runner
    version: ">0.0.0"
    condition: trento-runner.enabled
  - name: postgresql
    version: ~10.1.4
    repository: https://charts.bitnami.com/bitnami/
    condition: postgresql.enabled
