### Global Values ###
global:
  logLevel: info
  trentoWeb:
    name: web
    servicePort: 8080
  postgresql:
    name: postgresql
    servicePort: 5432

### Sub Charts Specific Values ###
trento-web:
  nameOverride: web
  enabled: true

trento-runner:
  nameOverride: runner
  enabled: true

postgresql:
  enabled: true
  image:
    tag: 14.1.0-debian-10-r30
  postgresqlUsername: "postgres"
  postgresqlPassword: "postgres"
  postgresqlDatabase: "trento"
