name: 'Consul cleanup'
description: 'Stop and delete consul data'
runs:
  using: "composite"
  steps:
    - name: stop-consul
      run: sudo systemctl stop consul
      shell: bash
    - name: delete-data
      run: sudo rm -rf /srv/consul/data
      shell: bash
