---

- name: gather facts
  ansible.builtin.setup:
  register: facts_result

- name: load environment variables
  include_vars: "{{ env | default('azure') }}_env.yml"
  delegate_to: localhost
  run_once: true

- name: set default value to cluster_selected_checks_list
  set_fact:
    cluster_selected_checks_list: "{{ cluster_selected_checks|default('')|split(',') }}"

- name: debug loaded vars
  debug:
    var: expected
    verbosity: 1

- name: Get corosync configuration file content
  command: md5sum /etc/corosync/corosync.conf
  register: corosync_md5_content

- name: Set corosync configuration file content
  set_fact:
    corosync_file_md5: "{{ corosync_md5_content.stdout }}"
  delegate_facts: True
